---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "netshoot2"
  labels:
    app.kubernetes.io/name: "netshoot2"
    app.kubernetes.io/component: "deployment.netshoot2"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/component: "deployment.netshoot2"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/name: "netshoot2"
        app.kubernetes.io/component: "deployment.netshoot2"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      containers:
      - name: "netshoot2"
        image: "nicolaka/netshoot:latest"
        command:
        - "sleep"
        - "3600"
        args: []
        imagePullPolicy: "Always"
